### ISSUE TITLE
What is the point of cohorts_provider class

### ISSUE THREAD

**Issue by mudrd8mz** [JosePFs/moodle-block_horario#5]
I can't understand what is the point of the whole `cohorts_provider_interface` and `cohorts_provider`. It all looks like unnecessary wrapper around the standard moodle core API `cohort_get_all_cohorts()` at the end. Am I missing something?

**Comment by mudrd8mz** [comment]
Especially as other cohort API calls (such as `cohort_is_member()`) as used natively. I know is is tempting to abstract on things via interfaces etc. But sometimes it only makes the code harder to read.

**Comment by JosePFs** [comment]
Thank you again mudrd8mz,
total agree...that interfaces make code innecesary harder...I moved responsability to a method in the service.
