### ISSUE TITLE
Default behaviour for not-in-cohort users

### ISSUE THREAD

**Issue by mudrd8mz** [JosePFs/moodle-block_horario#7]
If the current $USER is not a member of the defined cohort, then `user_is_not_in_cohort()` returns true and in turn `user_can_view_course()` returns true too.

As a result, the default behaviour for not-in-cohort users is that they can always see the course.

I am not sure if this is intuitive behaviour.

**Comment by JosePFs** [comment]
Hi mudrd8mz,
Ok, now if a user is not in cohort (s)he can't access to course
